server:
  servlet:
    context-path: /cvtoolapi

spring:
  datasource:
    url: jdbc:mariadb://${db.server}:${db.port}/CVTOOL
    username: ${db.user}
    password: ${ENV_DB_PASS}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include:
        - health

openapi:
  url: https://api.openai.com/v1/chat/completions
  token: ${OPENAPI_TOKEN}
  model: gpt-3.5-turbo
